Object.defineProperty(exports, "__esModule", {
  value: true
});
var NOTES_REQUEST = exports.NOTES_REQUEST = 'NOTES_REQUEST';
var NOTES_SUCCESS = exports.NOTES_SUCCESS = 'NOTES_SUCCESS';
var NOTES_FAIL = exports.NOTES_FAIL = 'NOTES_FAIL';
var ELEMENT_MENU_VISIBILITY = exports.ELEMENT_MENU_VISIBILITY = 'ELEMENT_MENU_VISIBILITY';