Object.defineProperty(exports, "__esModule", {
  value: true
});
var EDITOR_OPEN = exports.EDITOR_OPEN = 'EDITOR_OPEN';
var EDITOR_NEW = exports.EDITOR_NEW = 'EDITOR_NEW';
var EDITOR_SAVE_REQUEST = exports.EDITOR_SAVE_REQUEST = 'EDITOR_SAVE_REQUEST';
var EDITOR_SAVE_SUCCESS = exports.EDITOR_SAVE_SUCCESS = 'EDITOR_SAVE_SUCCESS';
var EDITOR_CHANGE_HEADER = exports.EDITOR_CHANGE_HEADER = 'EDITOR_CHANGE_HEADER';
var EDITOR_CHANGE_TEXT = exports.EDITOR_CHANGE_TEXT = 'EDITOR_CHANGE_TEXT';
var EDITOR_CHANGE_MODE = exports.EDITOR_CHANGE_MODE = 'EDITOR_CHANGE_MODE';
var EDITOR_DELETE_REQUEST = exports.EDITOR_DELETE_REQUEST = 'EDITOR_DELETE_REQUEST';
var EDITOR_DELETE_SUCCESS = exports.EDITOR_DELETE_SUCCESS = 'EDITOR_DELETE_SUCCESS';
var EDITOR_CHANGE_COLOR = exports.EDITOR_CHANGE_COLOR = 'EDITOR_CHANGE_COLOR';
var EDITOR_CLOSE = exports.EDITOR_CLOSE = 'EDITOR_CLOSE';
var EDITOR_CHANGE_COMPLETED = exports.EDITOR_CHANGE_COMPLETED = 'EDITOR_CHANGE_COMPLETED';